### ISSUE TITLE
Too broad permissions

### ISSUE THREAD

**Issue by sschizas** [justeat/PRAssigner#1]
Hello @andreaantonioni, I was looking into integrating the PRAssigner into our workflow. As described in the documentation, a question was raised about the number of permissions required. Does this tool require all of them? Also, do they need to have such a broad scope ex. `IAMFullAccess `, `AmazonS3FullAccess ` ?

**Comment by andreaantonioni** [comment]
Hi @sschizas, sorry for the delay. Unfortunately, I left Just Eat in the meanwhile and I lost a bit of context on PR Assigner.
I remember I checked permissions level before open-sourcing the code. If you think some permissions are too broad, you can make a test and limit them to see if PR Assigner still works as expected

**Comment by albertodebortoli** [comment]
Hi @sschizas and @andreaantonioni, we have moved away from PR Assigner and are not supporting this component anymore. I'm gonna go ahead and close this as well as deprecating and archiving the repo.
